Add set of default brew cask to speed up laptop setup

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -57,12 +57,50 @@ run_brew() {
         # install separately from the main formulae list to fix gh-19
         brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb
 
+        e_header "Checking status of desired Homebrew cask..."
+        local list_cask
+        local -a missing_cask
+        local -a desired_cask=(
+            'atom'
+            'iterm2'
+            'docker' # docker for mac
+            'alfred'
+            'spectacle'
+            '1password'
+            'google-backup-and-sync'
+            'evernote'
+            'spotify'
+            'google-chrome'
+            'electronic-wechat'
+        )
+
+        for index in ${!desired_cask[*]}
+        do
+            if ! cask_exists ${desired_cask[$index]}; then
+                # Store the name (and options) of every missing formula
+                missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
+            fi
+        done
+
+        if [[ "$missing_cask" ]]; then
+            # Convert the array of missing casks into a list of space-separate strings
+            list_cask=$( printf "%s " "${missing_cask[@]}" )
+
+            e_header "Installing missing Homebrew cask..."
+            # Install all missing cask
+            brew cask install $list_cask
+
+            [[ $? ]] && e_success "Done"
+        fi
+
         # Remove outdated versions from the Cellar
         brew cleanup
+        brew cask cleanup
     else
         printf "\n"
         e_error "Error: Homebrew not found."
         printf "Aborting...\n"
+        printf "Go to https://brew.sh/"
         exit
     fi
 
