Fix brew

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -15,8 +15,8 @@ run_brew() {
         [[ $? ]] && e_success "Done"
 
         e_header "Checking status of desired Homebrew formulae..."
-        local list_formulae
-        local -a missing_formulae
+        local list_brew
+        local -a missing_brew
         local -a desired_formulae=(
             'coreutils' # GNU core utilities (those that come with OS X are outdated)
             'git'
@@ -36,30 +36,13 @@ run_brew() {
 
         for index in ${!desired_formulae[*]}
         do
-            if ! formula_exists ${desired_formulae[$index]}; then
+            if ! formula_or_cask_exists ${desired_formulae[$index]}; then
                 # Store the name (and options) of every missing formula
-                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
+                missing_brew=("${missing_brew[@]}" "${desired_formulae[$index]}")
             fi
         done
 
-        if [[ "$missing_formulae" ]]; then
-            # Convert the array of missing formula into a list of space-separate strings
-            list_formulae=$( printf "%s " "${missing_formulae[@]}" )
-
-            e_header "Installing missing Homebrew formulae..."
-            # Install all missing formulae
-            brew install $list_formulae
-
-            [[ $? ]] && e_success "Done"
-        fi
-
-        # use latest rsync rather than out-dated OS X rsync
-        # install separately from the main formulae list to fix gh-19
-        brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb
-
         e_header "Checking status of desired Homebrew cask..."
-        local list_cask
-        local -a missing_cask
         local -a desired_cask=(
             'docker' # docker for mac
             'alfred'
@@ -78,22 +61,26 @@ run_brew() {
 
         for index in ${!desired_cask[*]}
         do
-            if ! cask_exists ${desired_cask[$index]}; then
+            if ! formula_or_cask_exists ${desired_cask[$index]}; then
                 # Store the name (and options) of every missing formula
-                missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
+                missing_brew=("${missing_brew[@]}" "${desired_cask[$index]}")
             fi
         done
 
-        if [[ "$missing_cask" ]]; then
-            # Convert the array of missing casks into a list of space-separate strings
-            list_cask=$( printf "%s " "${missing_cask[@]}" )
+        if [[ "$missing_brew" ]]; then
+            # Convert the array of missing brews into a list of space-separate strings
+            list_brew=$( printf "%s " "${missing_brew[@]}" )
 
-            e_header "Installing missing Homebrew cask..."
-            # Install all missing cask
-            brew install --cask $list_cask
+            e_header "Installing missing Homebrew formulae..."
+            # Install all missing formulae
+            brew install $list_brew
 
             [[ $? ]] && e_success "Done"
         fi
+
+        # use latest rsync rather than out-dated OS X rsync
+        # install separately from the main formulae list to fix gh-19
+        brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb
 
         # Remove outdated versions from the Cellar
         brew cleanup
